name: Terraform-Workflow
on: push

jobs:
    installation-code:

        name: Installation Terraform and AWS Cli
        runs-on: ubuntu-latest
        steps:
            - name: Checkout to github
              uses: actions/checkout@v4
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
               terraform_version: 1.12.2 # Specify your desired Terraform version

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
               aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Use the secret you stored
               aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Use the secret you stored
               aws-region: us-east-1 # Specify your AWS region

            - name: Checking aws cli
              run: |
               aws --version

    ec2-creation:
        name: Creating ec2 instance
        runs-on: ubuntu-latest
        needs: installation-code
        defaults:
          run:
            working-directory: ./terraform
        steps:
            - name: Initating ec2 creation
              run: |
               terraform init
               terraform apply -auto-approve
              
                
